### ISSUE TITLE
Doesn't work in Karma

### ISSUE THREAD

**Issue by volkanunsal** [jhnns/rewire-webpack#14]
I'm trying to integrate rewire into Karma, and it keeps failing me.

    ReferenceError: Can't find variable: rewire in .../assets/karma.tests.js (line 147)

Why? I don't know. Here is my configuration files:

```javascript
// webpack.config.js
var RewirePlugin = require('rewire-webpack');
config.plugins.push(new RewirePlugin());
```

```javascript
// karma.config.js
plugins: [
      'rewire-webpack'
]
```

I did everything right, I think. But still doesn't work...

**Comment by munnerz** [comment]
Did you ever come to a resolution with this? I'm currently having the same issue.
