### ISSUE TITLE
Error: No module factory available for dependency type: Dependency

### ISSUE THREAD

**Issue by scottburch** [jhnns/rewire-webpack#19]
I have created a small sandbox here that shows the error with minimal code
https://github.com/scottburch/rewire-error
To reproduce:
npm install
webpack

I have found that webpack 1.12.2 works, 1.12.3 does not.

**Comment by scottburch** [comment]
I thought I would copy this response from the webpack folks here so that others who search issues for rewire-webpack might see this also.


@jhnns This require a change to rewire-webpack. A Dependency must correctly have a constructor property on it's prototype. The Class property is not needed anymore.

**Comment by scottburch** [comment]
@jhnns I tested the newest master and it seems to work, looks like it just has not been published on NPM.  If it is ready, please publish.  Thanks.

**Comment by jhnns** [comment]
Thank you for reporting it. This has been fixed with `1.0.1`
